<!doctype html>
<!-- Generated by scripts/build_site.py; edit template/index.html.tpl and data/locales.json. -->
<html lang="$html_lang" class="lang-$lang">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <meta name="description" content="$description">
  <link rel="canonical" href="$canonical">
  $alternates
  <meta property="og:type" content="profile">
  <meta property="og:title" content="$title">
  <meta property="og:description" content="$og_description">
  <meta property="og:url" content="$canonical">
  <meta property="og:image" content="https://wei-lee.me/images/avatar.jpg">
  <meta property="og:image:alt" content="$image_alt">
  <meta property="og:locale" content="$og_locale">
  $og_alternates
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="$title">
  <meta name="twitter:image" content="https://wei-lee.me/images/avatar.jpg">
  <meta name="theme-color" content="#f4f2ec" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#181816" media="(prefers-color-scheme: dark)">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
  <link rel="icon" type="image/png" sizes="512x512" href="/favicon-512.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&amp;family=Noto+Sans+JP:wght@400;500;700&amp;family=Noto+Sans+TC:wght@400;500;700&amp;family=Noto+Serif+JP:wght@700&amp;family=Noto+Serif+TC:wght@700&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
  <link rel="stylesheet" href="/css/home.css">
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Person",
    "name": "Wei Lee",
    "alternateName": "李唯",
    "url": "https://wei-lee.me/",
    "image": "https://wei-lee.me/images/avatar.jpg",
    "email": "mailto:hello@wei-lee.me",
    "jobTitle": $job_title_json,
    "nationality": $nationality_json,
    "sameAs": [
      "https://github.com/Lee-W/",
      "https://tw.linkedin.com/in/clleew",
      "https://twitter.com/clleew",
      "https://g0v.social/@weilee",
      "https://blog.wei-lee.me/",
      "https://travlog.wei-lee.me/"
    ]
  }
  </script>
  <script data-goatcounter="https://wei-lee.goatcounter.com/count"
          async src="//gc.zgo.at/count.js"></script>
</head>
<body>
  <main class="page">
    <div class="topbar">
      <div class="lang-switcher" role="group" aria-label="$language_label">
        $language_options
      </div>
    </div>

    <header class="identity">
      <img class="avatar" src="/images/avatar.jpg" alt="" width="82" height="82">
      <div class="identity-copy">
        <h1>
          <span data-lang="zh">李唯 <span class="name-alt">/ Wei Lee</span></span>
          <span data-lang="en">Wei Lee <span class="name-alt">/ 李唯</span></span>
          <span data-lang="ja"><ruby>李<rp>(</rp><rt>リ</rt><rp>)</rp>唯<rp>(</rp><rt>ウェ</rt><rp>)</rp></ruby> <span class="name-alt">/ Wei Lee</span></span>
        </h1>
        <p class="bio">
          <span data-lang="$lang">$bio</span>
        </p>
      </div>
    </header>

    <nav class="paths" aria-label="$paths_label">
      <a id="aboutLink" class="path path-about" href="https://blog.wei-lee.me$blog_language_path/pages/about-me" rel="noopener noreferrer">
        <span class="role-icon glyph path-icon" aria-hidden="true">◔</span>
        <span class="path-title"><span data-lang="$lang">$about</span></span>
        <span class="path-subtitle"><span data-lang="$lang">$about_subtitle</span></span>
        <span class="path-arrow" aria-hidden="true">›</span>
      </a>
      <a class="path path-tech" href="https://blog.wei-lee.me/" rel="noopener noreferrer">
        <span class="role-icon glyph path-icon" aria-hidden="true">✎</span>
        <span class="path-title"><span data-lang="$lang">$tech_title</span></span>
        <span class="path-subtitle"><span data-lang="$lang">$tech_subtitle</span></span>
        <span class="path-arrow" aria-hidden="true">›</span>
      </a>
      <a class="path path-life" href="https://travlog.wei-lee.me/" rel="noopener noreferrer">
        <span class="role-icon glyph path-icon" aria-hidden="true">🧭</span>
        <span class="path-title"><span data-lang="$lang">$life_title</span></span>
        <span class="path-subtitle"><span data-lang="$lang">$life_subtitle</span></span>
        <span class="path-arrow" aria-hidden="true">›</span>
      </a>
    </nav>

    <a id="nowLink" class="now" href="https://blog.wei-lee.me$blog_language_path/pages/now" rel="noopener noreferrer">
      <span class="role-icon glyph now-icon" aria-hidden="true">◷</span>
      <span>
        <strong><span data-lang="$lang">$now</span></strong>
        <span class="now-detail"><span data-lang="$lang">$now_detail</span></span>
      </span>
      <span class="now-arrow" aria-hidden="true">→</span>
    </a>

    <section class="blogs" aria-label="$blogs_label">
      <article class="blog-card tech">
        <div class="blog-head">
          <div>
            <h2><a href="https://blog.wei-lee.me/" rel="noopener noreferrer"><span data-lang="$lang">$tech_blog</span></a></h2>
          </div>
          <a class="rss" href="https://blog.wei-lee.me/feeds/all.atom.xml" aria-label="$tech_rss_label"><i class="fa-solid fa-rss" aria-hidden="true"></i></a>
        </div>
        <ul class="posts">
          $tech_posts
        </ul>
      </article>

      <article class="blog-card life">
        <div class="blog-head">
          <div>
            <h2><a href="https://travlog.wei-lee.me/" rel="noopener noreferrer"><span data-lang="$lang">$life_blog</span></a></h2>
          </div>
          <a class="rss" href="https://travlog.wei-lee.me/feeds/all.atom.xml" aria-label="$life_rss_label"><i class="fa-solid fa-rss" aria-hidden="true"></i></a>
        </div>
        <ul class="posts">
          $life_posts
        </ul>
      </article>
    </section>

    <ul class="roles" aria-label="$roles_label">
      <li><span class="role-icon"><img src="/images/python.svg" alt=""></span><span data-lang="$lang">$python</span></li>
      <li><a href="https://tw.pycon.org/" rel="noopener noreferrer"><span class="role-icon pycon"><img src="/images/pycontw.svg" alt=""></span><span data-lang="$lang">$pycon</span></a></li>
      <li><a href="https://airflow.apache.org/" rel="noopener noreferrer"><span class="role-icon"><img src="/images/airflow.svg" alt=""></span><span data-lang="$lang">$airflow</span></a></li>
      <li><a href="https://github.com/commitizen-tools" rel="noopener noreferrer"><img class="role-icon" src="/images/commitizen.svg" alt=""><span data-lang="$lang">$commitizen</span></a></li>
      <li><a href="https://travlog.wei-lee.me/pages/pilgrimage" rel="noopener noreferrer"><img class="role-icon" src="/images/traveler.svg" alt=""><span data-lang="$lang">$traveler</span></a></li>
      <li><a href="https://twitter.com/Taiwannokuru" rel="noopener noreferrer"><span class="role-icon glyph" aria-hidden="true">⛺</span><span>台湾野クル▲</span></a></li>
      <li><a href="https://travlog.wei-lee.me/pages/story-ranking" rel="noopener noreferrer"><img class="role-icon" src="/images/anime.svg" alt=""><span data-lang="$lang">$anime</span></a></li>
      <li><a href="https://blog.wei-lee.me/category/book" rel="noopener noreferrer"><span class="role-icon glyph" aria-hidden="true">📖</span><span data-lang="$lang">$books</span></a></li>
      <li><span class="role-icon glyph" aria-hidden="true">♪</span><span data-lang="$lang">$ukulele</span></li>
      <li><span class="role-icon glyph" aria-hidden="true">🔒</span><span>Locker</span></li>
    </ul>

    <nav class="social" aria-label="$social_label">
      <a href="mailto:hello@wei-lee.me"><i class="fa-regular fa-envelope" aria-hidden="true"></i><span>Email</span></a>
      <a href="https://github.com/Lee-W/" rel="noopener noreferrer"><i class="fa-brands fa-github" aria-hidden="true"></i><span>GitHub</span></a>
      <a href="https://tw.linkedin.com/in/clleew" rel="noopener noreferrer"><i class="fa-brands fa-linkedin" aria-hidden="true"></i><span>LinkedIn</span></a>
      <a href="https://twitter.com/clleew" rel="noopener noreferrer"><i class="fa-brands fa-twitter" aria-hidden="true"></i><span>Twitter</span></a>
      <a href="https://g0v.social/@weilee" rel="noopener noreferrer"><i class="fa-brands fa-mastodon" aria-hidden="true"></i><span>Mastodon</span></a>
      <a href="/card/?utm_source=home"><i class="fa-regular fa-address-card" aria-hidden="true"></i><span data-lang="$lang">$card</span></a>
    </nav>
  </main>
  <script src="/js/home.js"></script>
</body>
</html>
